nama: TCH NANDAYO KOITSE

pada: workflow_dispatch

pekerjaan:
  membangun:

    berjalan-on: windows-terbaru
    batas waktu-menit: 9999

    Langkah:
    - nama : Download Ngrok.
      jalankan: |
        Panggil-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Panggil-WebRequest https://raw.githubusercontent.com/RavensVenix/Free-RDP/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/RavensVenix/Free-RDP/main/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/RavensVenix/Free-RDP/main/wallpaper.bat -OutFile wallpaper.bat
    - nama : Mengekstrak File Ngrok.
      jalankan: Perluas-Arsip ngrok.zip
    - nama : Menghubungkan ke akun Ngrok Anda.
      jalankan: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      lingkungan:
        NGROK_AUTH_TOKEN: ${{ rahasia.NGROK_AUTH_TOKEN }}
    - nama : Mengaktifkan akses RDP.
      jalankan: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-nama "fDenyTSConnections" -Nilai 0
        Aktifkan-NetFirewallRule -DisplayGroup "Desktop Jarak Jauh"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -nama "UserAuthentication" -Nilai 1
        salin wallpaper.png D:\a\wallpaper.png
        salin wallpaper.bat D:\a\wallpaper.bat
    - nama : Membuat Terowongan.
      jalankan: Mulai-Proses Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - nama: Menghubungkan ke RDP Anda.
      jalankan: cmd /c start.bat
    - nama: RDP sudah siap!
      jalankan: |
        Panggil-WebRequest https://github.com/RavensVenix/Free-RDP/raw/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
